import pandas as pd
from src.conexao import get_engine

eng = get_engine()

sql = """
WITH Base AS (
    SELECT
        i.VLRTOTAL,
        CASE WHEN fs.VALOR IS NOT NULL THEN 1 ELSE 0 END AS IS_SAIDA,
        CASE WHEN fe.VALOR IS NOT NULL THEN 1 ELSE 0 END AS IS_DEV,
        CASE WHEN fm.VALOR IS NOT NULL THEN 1 ELSE 0 END AS IS_MATERIAL_FILTRADO
    FROM FN_NFS n
    JOIN FN_NFSITENS i ON i.NFS = n.CODIGO
    LEFT JOIN FN_FORNECEDORES f ON f.CODIGO = n.CLIENTE

    JOIN GR_FILTROITENSUSUARIOCONTIDO fdoc
      ON fdoc.FILTROITEM = 6959
     AND fdoc.USUARIO = 124
     AND fdoc.VALOR = n.TPDOCUMENTO

    JOIN GR_FILTROITENSUSUARIOCONTIDO fst
      ON fst.FILTROITEM = 6965
     AND fst.USUARIO = 124
     AND fst.VALOR = n.STATUSNF

    JOIN GR_FILTROITENSUSUARIOCONTIDO fuf
      ON fuf.FILTROITEM = 6962
     AND fuf.USUARIO = 124
     AND fuf.VALOR = ISNULL(f.UF, '')

    LEFT JOIN GR_FILTROITENSUSUARIOCONTIDO fs
      ON fs.FILTROITEM = 6958
     AND fs.USUARIO = 124
     AND fs.VALOR = i.CFOP

    LEFT JOIN GR_FILTROITENSUSUARIOCONTIDO fe
      ON fe.FILTROITEM = 6966
     AND fe.USUARIO = 124
     AND fe.VALOR = i.CFOP

    LEFT JOIN GR_FILTROITENSUSUARIOCONTIDO fm
      ON fm.FILTROITEM = 6963
     AND fm.USUARIO = 124
     AND fm.VALOR = i.MATERIAL

    WHERE n.DTEMISSAO >= '2026-01-01'
      AND n.DTEMISSAO < '2026-02-01'
)
SELECT
    'COM_MATERIAL_528' AS CENARIO,
    SUM(CASE WHEN IS_SAIDA = 1 THEN ISNULL(VLRTOTAL, 0) ELSE 0 END) AS SAIDAS,
    SUM(CASE WHEN IS_DEV = 1 THEN ISNULL(VLRTOTAL, 0) ELSE 0 END) AS DEVOLUCOES,
    SUM(CASE
            WHEN IS_SAIDA = 1 THEN ISNULL(VLRTOTAL, 0)
            WHEN IS_DEV = 1 THEN -ISNULL(VLRTOTAL, 0)
            ELSE 0
        END) AS TOTAL_LIQ
FROM Base
WHERE IS_MATERIAL_FILTRADO = 1

UNION ALL

SELECT
    'SEM_MATERIAL_528' AS CENARIO,
    SUM(CASE WHEN IS_SAIDA = 1 THEN ISNULL(VLRTOTAL, 0) ELSE 0 END) AS SAIDAS,
    SUM(CASE WHEN IS_DEV = 1 THEN ISNULL(VLRTOTAL, 0) ELSE 0 END) AS DEVOLUCOES,
    SUM(CASE
            WHEN IS_SAIDA = 1 THEN ISNULL(VLRTOTAL, 0)
            WHEN IS_DEV = 1 THEN -ISNULL(VLRTOTAL, 0)
            ELSE 0
        END) AS TOTAL_LIQ
FROM Base
"""

df = pd.read_sql(sql, eng)
print(df.to_string(index=False))
